### ISSUE TITLE
Startup and persistence

### ISSUE THREAD

**Issue by Moistfloor** [cisamu123/CyberEye#1]
it seems to disconnect completely after around 30 minutes, even if I put it in exceptions or run it as admin. And if you restart the computer its gone too.

**Comment by cisamu123** [comment]
Idk, i think that's problem with ur pc. I tested this RAT on my VM and all worked successfully or i also think ur antivirus starting after pc restarting. ** I'm sorry that's problem with ur pc or ur antivirus, i cant solve that.**
